version: '3.1'
networks:
  bridgednetwork:
    driver: bridge

services:

  postgresdb:
    image: "postgres"
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: test
      POSTGRES_DB: sqlalchemy
    networks:
      - bridgednetwork
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5