version: '2.1'
networks:
  postgresnetwork:
    driver: bridge

services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    links:
      - db
    networks:
      - postgresnetwork
    depends_on:
      db:
        condition: service_healthy
  redis:
    image: "redis:alpine"

  db:
    image: "postgres"
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: test
      POSTGRES_DB: sqlalchemy
    networks:
      - postgresnetwork
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
